vich_uploader:
    db_driver: orm

    mappings:
        oh_items:
            uri_prefix: /images/once-human/items
            upload_destination: '%kernel.project_dir%/public/images/once-human/items'
            namer: Vich\UploaderBundle\Naming\Base64Namer
    
