# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    automation.token: '%env(AUTOMATION_TOKEN)%'
    patreon.client.id: '%env(PATREON_CLIENT_ID)%'
    patreon.client.secret: '%env(PATREON_CLIENT_SECRET)%'
    twitch.client.id: '%env(TWITCH_CLIENT_ID)%'
    twitch.client.secret: '%env(TWITCH_CLIENT_SECRET)%'
    uploads_directory: '%kernel.project_dir%/public/uploads'
    uploads.enshrouded_item_icon_dir: '/uploads/api/enshrouded/items'
    uploads.enshrouded_npc_icon_dir: '/uploads/api/enshrouded/npcs'
    uploads.vestigia_item_dir: '/uploads/api/vestigia/items'
    vestigia.item.rarity:
        common: Commun
        uncommon: Non commun
        rare: Rare
        epic: Épique
        legendary: Légendaire
    vestigia.item.type:
          currency: Monnaie
          consumable: Consommable
          material: Matériaux
          equipment: Équipement
          cosmetic: Cosmétique
          quest: Quête
    vestigia.character.defaults:
        hpMin: 100
        hpMax: 100
        atk: 10
        def: 15
        apMin: 100
        apMax: 100
    sites:
        - name: 'API de Thoanny'
          description: 'API et interface de gestion de données des différentes applications'
          url: 'https://api.thoanny.fr'
          domain: 'api.thoanny.fr'
        - name: 'Dune: Awakening (fansite)'
          description: 'Outils pour le landsraad : progression, Grandes Maisons et skins d''objets débloqués'
          url: 'https://dune.thoanny.fr'
          domain: 'dune.thoanny.fr'
        - name: 'Enshrouded (fansite)'
          description: 'Base de données d''objets, de recettes et liens utiles de Valdebraise'
          url: 'https://enshrouded.vercel.app'
          domain: 'enshrouded.vercel.app'
        - name: 'Loftia (fansite)'
          description: 'Outil pour suivre la progression des dons aux stations de recherches'
          url: 'https://loftia.thoanny.fr'
          domain: 'loftia.thoanny.fr'
        - name: 'Générateur de planning'
          description: 'Générateur de planning Twitch personnalisé et gratuit, à diffuser sur vos réseaux sociaux numériques'
          url: 'https://planning.thoanny.fr'
          domain: 'planning.thoanny.fr'
    

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventListener\VichImageListener:
        tags:
            - { name: kernel.event_listener, event: vich_uploader.post_upload }
    
    gedmo.mapping.driver.attribute:
        class: Gedmo\Mapping\Driver\AttributeReader
        
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_listener, event: 'prePersist' }
            - { name: doctrine.event_listener, event: 'preUpdate' }
            - { name: doctrine.event_listener, event: 'preRemove' }
            - { name: doctrine.event_listener, event: 'onFlush' }
            - { name: doctrine.event_listener, event: 'loadClassMetadata' }
            - { name: doctrine.event_listener, event: 'postPersist' }
            - { name: doctrine.event_listener, event: 'postUpdate' }
            - { name: doctrine.event_listener, event: 'postRemove' }
        calls:
            # Uncomment the below call if using attributes, and comment the call for the annotation reader
             - [ setAnnotationReader, [ '@gedmo.mapping.driver.attribute' ] ]
            # The `annotation_reader` service was deprecated in Symfony 6.4 and removed in Symfony 7.0
#            - [ setAnnotationReader, [ '@annotation_reader' ] ]
    
